batch_size: 32
config_type: xgb_correlation
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: room_layout
out_dir: run
predictor: 400
search_space: transbench101_macro
seed: 9008
test_size: 200
train_portion: 0.7
train_size: 400
zc_ensemble: true
zc_names:
- flops
- params
- snip
- jacov
- grad_norm
- plain
- epe_nas
- fisher
- grasp
- l2_norm
zc_only: true
