
# experiment types: single, vary_train_size, vary_fidelity
experiment_type: single
search_space: nasbench201
predictor: xgb
test_size: 200
uniform_random: 1
seed: 1000
max_hpo_time: 0

dataset: cifar10
out_dir: run

train_size_list: [8, 12, 20, 32, 50, 80, 128, 203, 322, 512]
train_size_single: 100

fidelity_list: [5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190]
fidelity_single: 5

# Used by Jacobian_cov from NAS without training from DARTS for data loader
search:
  seed: 1000
  batch_size: 256 # modified based on NAS with training paper
  data_size: 25000
  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
  train_portion: 0.7

