dataset: cifar10
seed: 0
search_space: nasbench201
out_dir: /work/dlclarge2/agnihotr-ml/nas301_test_acc/NASLib/naslib/optimizers/oneshot/move/runs/testing/again_0.95
optimizer: movement
method: drop_one

search:
 
  # MOVEMENT
  instantenous: False
  epochs: 24
  warm_start_epochs: 5
  masking_interval: 1
  train_portion: 0.95
  data_size: 47500
  batch_size: 128
  perform_fgsm: True
  fgsm_epsilon: 0.2
  large_nets: True
  large_nets_coefficient: 1.0
  
  # BANANAS
  k: 10
  num_ensemble: 3
  acq_fn_type: its
  acq_fn_optimization: mutation
  encoding_type: path
  num_arches_to_mutate: 2
  max_mutations: 1
  num_candidates: 100
  
  # BasePredictor
  predictor_type: var_sparse_gp
  debug_predictor: False

  # GDAS
  tau_max: 10
  tau_min: 0.1

  # RE
  sample_size: 10
  population_size: 100
  
  #LS
  num_init: 10

  #Cutout
  cutout: False
  cutout_length: 16
  cutout_prob: 1.0
  drop_path_prob: 0.2
  auxiliary_weight: 0.4

  #Extras
  unrolled: False
  arch_learning_rate: 0.0003
  arch_weight_decay: 0.001
  output_weights: True
  fidelity: 200
  

  #GMovement
  checkpoint_freq: 30
  grad_clip: 0
  threshold: 0.000001
  weight_decay: 0.001
  learning_rate: 0.01
  momentum: 0.8
  normalization: div
  normalization_exponent: 0.5
  
  learning_rate_min: 0.0001
  



evaluation:
  checkpoint_freq: 30
  batch_size: 96
  learning_rate: 0.025
  learning_rate_min: 0.00
  momentum: 0.9
  weight_decay: 0.0003
  epochs: 200
  warm_start_epochs: 0
  grad_clip: 5
  train_portion: 1.
  data_size: 50000

  cutout: True
  cutout_length: 16
  cutout_prob: 1.0
  drop_path_prob: 0.2
  auxiliary_weight: 0.4
