batch_size: 32
config_type: correlation
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: ImageNet16-120
out_dir: run
predictor: jacov
search_space: nasbench201
seed: 9001
test_size: 200
train_portion: 0.7
