batch_size: 32
config_type: zc_and_adjacency
cutout: false
cutout_length: 16
cutout_prob: 1.0
dataset: cifar100
fidelity: -1
optimizer: bananas
out_dir: run
predictor: zc
search:
  acq_fn_optimization: mutation
  acq_fn_type: its
  checkpoint_freq: 1001
  encoding_type: adjacency
  epochs: 500
  k: 10
  max_mutations: 1
  num_arches_to_mutate: 2
  num_candidates: 100
  num_ensemble: 1
  num_init: 10
  predictor_type: xgb
  seed: 9400
  use_zc_api: true
  zc: true
  zc_ensemble: true
  zc_names:
  - flops
  - params
  - snip
  - jacov
  - grad_norm
  - plain
  - fisher
  - grasp
  - l2_norm
  - nwot
  - zen
  - epe_nas
  - synflow
  zc_only: true
search_space: nasbench201
seed: 9400
test_size: 1000
train_portion: 0.7
